export const RESTAURANT_ERP = {
  slug: "restaurant-erp",
  liveDemoHref: "https://restaurant-resource-planning-system.vercel.app/",
  title: "Restaurant ERP Platform",
  subtitle:
    "Enterprise Restaurant ERP Platform built with React, FastAPI, PostgreSQL, Redis, Docker and AWS Cloud Infrastructure.",
  overview: [
    "Restaurant ERP Platform is an enterprise-grade business management solution developed to centralize restaurant operations across multiple restaurant locations.",
    "The platform streamlines authentication, restaurant administration, inventory, procurement, supplier management, executive dashboards, reporting, billing workflows, and operational analytics.",
    "The application follows cloud-native architecture and is designed for scalable enterprise deployment on Amazon Web Services.",
  ],
  badges: [
    "AWS",
    "Cloud Native",
    "Enterprise",
    "Docker",
    "Infrastructure as Code",
    "Amazon ECS",
    "Amazon RDS",
    "Amazon ECR",
    "Redis",
    "FastAPI",
    "React",
  ],
  techStack: [
    "React",
    "Vite",
    "Tailwind CSS",
    "FastAPI",
    "Python",
    "PostgreSQL",
    "Redis",
    "Docker",
    "Amazon ECS",
    "Amazon ECR",
    "Amazon RDS",
    "Amazon ElastiCache",
    "Amazon VPC",
    "AWS IAM",
    "AWS Secrets Manager",
    "AWS CDK",
    "CloudFormation",
    "AWS CLI",
  ],
  deployment: [
    "Enterprise deployment using Docker and AWS cloud infrastructure.",
    "Infrastructure provisioned with AWS CDK and CloudFormation.",
    "Containerized services deployed using Amazon ECS (Fargate).",
    "Persistent data managed with Amazon RDS PostgreSQL.",
    "High-performance caching using Amazon ElastiCache Redis.",
    "Secure networking with Amazon VPC.",
    "Secrets managed through AWS Secrets Manager.",
  ],
  features: [
    "Restaurant Management",
    "Inventory",
    "Procurement",
    "Supplier Management",
    "Order Processing",
    "Executive Dashboard",
    "Analytics",
    "Reporting",
    "JWT Authentication",
    "Role Based Access Control",
    "Cloud Native Architecture",
    "Enterprise Scalability",
  ],
  challenges: [
    "Cloud architecture design",
    "Docker containerization",
    "Infrastructure as Code",
    "AWS networking",
    "IAM security",
    "Secrets management",
    "Database scalability",
    "Redis caching",
    "Enterprise deployment strategy",
  ],
  delivered: [
    "Enterprise-grade cloud architecture",
    "Dockerized application",
    "Infrastructure as Code",
    "Scalable backend services",
    "Secure AWS networking",
    "Production-ready deployment architecture",
  ],
  architectureLayers: [
    {
      id: "edge",
      label: "Edge & Traffic",
      nodes: [
        { id: "browser", name: "Browser", subtitle: "Client applications" },
        { id: "alb", name: "Application Load Balancer", subtitle: "Amazon ELB" },
      ],
    },
    {
      id: "compute",
      label: "Compute",
      nodes: [
        { id: "ecs", name: "Amazon ECS", subtitle: "Fargate" },
        { id: "api", name: "FastAPI Backend", subtitle: "Application services" },
      ],
    },
    {
      id: "data",
      label: "Data Plane",
      nodes: [
        { id: "rds", name: "Amazon RDS", subtitle: "PostgreSQL" },
        { id: "redis", name: "Amazon ElastiCache", subtitle: "Redis" },
      ],
    },
    {
      id: "containers",
      label: "Container Registry",
      nodes: [
        { id: "docker", name: "Docker Images", subtitle: "Containerized workloads" },
        { id: "ecr", name: "Amazon ECR", subtitle: "Image registry" },
      ],
    },
    {
      id: "iac",
      label: "Infrastructure",
      nodes: [
        { id: "cdk", name: "AWS CDK", subtitle: "Infrastructure as Code" },
        { id: "cfn", name: "CloudFormation", subtitle: "Provisioned stacks" },
      ],
    },
    {
      id: "network",
      label: "Networking",
      nodes: [{ id: "vpc", name: "Amazon VPC", subtitle: "Isolated network fabric" }],
    },
    {
      id: "security",
      label: "Security",
      nodes: [
        { id: "iam", name: "AWS IAM", subtitle: "Identity & access" },
        { id: "secrets", name: "AWS Secrets Manager", subtitle: "Credential vault" },
      ],
    },
  ],
} as const;

export type RestaurantErpCaseStudy = typeof RESTAURANT_ERP;
